diff --git a//dev/null b/oriundi-radar/config/settings.example.toml
index 0000000000000000000000000000000000000000..75e65da403baaf2289406fcae41edaa1bbff77b6 100644
--- a//dev/null
+++ b/oriundi-radar/config/settings.example.toml
@@ -0,0 +1,31 @@
+[anycrawl]
+enabled = false
+base_url = "https://api.anycrawl.dev/v1"
+key = "YOUR_ANYCRAWL_KEY"
+rate_limit_per_minute = 60
+
+[historical]
+enabled = true
+path = "data/historical_callups.csv"
+max_rows = 100
+
+[registry]
+enabled = true
+base_url = "https://data.example.com/registry"
+max_results = 250
+
+[storage]
+duckdb_path = "data/oriundi.duckdb"
+graph_store_path = "output/oriundi_graph.ttl"
+export_dir = "output"
+
+[ml]
+enable_language_models = false
+spacy_model = ""
+fuzzy_threshold = 88
+
+queries = [
+  "football dual citizenship prospect",
+  "youth player italian ancestry",
+  "san marino eligible footballer"
+]
