name: Daily Anomaly Radar

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"   # 07:00 UTC (09:00 CEST in estate)

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -V
          pip -V
          python -m pip install --upgrade pip
          pip install requests

      - name: Run anomaly engine
        env:
          ANYCRAWL_API_URL: ${{ secrets.ANYCRAWL_API_URL }}
          ANYCRAWL_API_KEY: ${{ secrets.ANYCRAWL_API_KEY }}
          SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
        run: |
          mkdir -p output
          python engine/run.py

      - name: Copy JSON to docs
        run: |
          mkdir -p docs
          cp output/daily.json docs/daily.json

      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/daily.json
          git commit -m "chore: update daily.json [skip ci]" || echo "No changes to commit"
          git push
